import {
  EventStreamContentType,
  fetchEventSource,
} from "@microsoft/fetch-event-source";
import type { AgentEvent } from "@/lib/events";
import type { TokenGetter } from "./client";
import { apiUrl } from "./config";
import { ApiError } from "./types";

export interface RunStreamHandlers {
  onEvent: (event: AgentEvent) => void;
  onError?: (err: unknown) => void;
  onClose?: () => void;
}

class RetriableError extends Error {}
class FatalError extends Error {}

/**
 * Start a run and stream it. Returns an abort function.
 *
 * The `runId` is generated by the caller and sent in the body so a
 * transient reconnect re-POSTs the same id and the backend attaches to
 * the in-flight run (with `Last-Event-ID` resume) instead of starting a
 * duplicate.
 */
export function openRunStream(
  convId: string,
  prompt: string,
  runId: string,
  getToken: TokenGetter,
  handlers: RunStreamHandlers,
  attachmentIds: string[] = [],
): () => void {
  return openStream(
    `/api/conversations/${convId}/runs`,
    {
      method: "POST",
      body: JSON.stringify({
        prompt,
        run_id: runId,
        attachment_ids: attachmentIds,
      }),
    },
    getToken,
    handlers,
  );
}

/**
 * Re-attach to a run that is already streaming server-side (after a page
 * reload or network drop). Replays the frames the client missed and then
 * continues live until the run ends. If nothing is streaming the backend
 * closes the stream immediately and `onClose` fires.
 */
export function attachRunStream(
  convId: string,
  getToken: TokenGetter,
  handlers: RunStreamHandlers,
): () => void {
  return openStream(
    `/api/conversations/${convId}/stream`,
    { method: "GET" },
    getToken,
    handlers,
  );
}

/**
 * Attach to a task run's SSE stream (plan 16 Phase 2). The mention POST is a
 * regular JSON request; the live trajectory is streamed here by run id. On a
 * reload / network drop we re-attach with `Last-Event-ID` and replay missed
 * frames. If the run already finished (and was evicted) the stream closes
 * immediately and `onClose` fires.
 */
export function attachTaskRunStream(
  runId: string,
  getToken: TokenGetter,
  handlers: RunStreamHandlers,
): () => void {
  return openStream(
    `/api/runs/${runId}/events`,
    { method: "GET" },
    getToken,
    handlers,
  );
}

/** A lightweight board-scoped event (see backend `BoardEventBus`). */
export interface BoardEvent {
  type: string;
  board_id: string;
  task_id?: string;
  agent_id?: string;
  run_id?: string;
  comment_id?: string;
  actor_id?: string;
  status?: string;
  /** "agent.typing" presence: who is typing + start/stop. */
  user_name?: string;
  state?: string;
}

/**
 * Subscribe to a board's realtime event feed (`/api/boards/{id}/stream`).
 * Events are small hints; the caller re-reads through the normal API. The
 * connection auto-reconnects on transient errors. Returns an abort fn.
 */
export function subscribeBoardEvents(
  boardId: string,
  getToken: TokenGetter,
  onEvent: (e: BoardEvent) => void,
): () => void {
  const ctrl = new AbortController();
  void fetchEventSource(apiUrl(`/api/boards/${boardId}/stream`), {
    method: "GET",
    signal: ctrl.signal,
    openWhenHidden: true,
    headers: { Accept: EventStreamContentType },
    async onopen(res) {
      const ct = res.headers.get("content-type") ?? "";
      if (res.ok && ct.includes(EventStreamContentType)) return;
      if (res.status === 401 || res.status === 429 || res.status >= 500) {
        throw new RetriableError(`board stream open failed: ${res.status}`);
      }
      throw new FatalError(`board stream failed: ${res.status}`);
    },
    onmessage(msg) {
      if (!msg.data) return;
      try {
        onEvent(JSON.parse(msg.data) as BoardEvent);
      } catch {
        /* ignore keep-alive comments / partial frames */
      }
    },
    onerror(err) {
      if (err instanceof FatalError) throw err;
      return 2000;
    },
    async fetch(input, init) {
      const token = await getToken();
      const headers = new Headers(init?.headers);
      if (token) headers.set("Authorization", `Bearer ${token}`);
      return fetch(input, { ...init, headers });
    },
  }).catch(() => {
    /* fatal — give up quietly; views still work via manual refetch */
  });
  return () => ctrl.abort();
}

function openStream(
  url: string,
  init: { method: string; body?: string },
  getToken: TokenGetter,
  handlers: RunStreamHandlers,
): () => void {
  const ctrl = new AbortController();
  let lastEventId = "";

  const headers: Record<string, string> = {
    Accept: EventStreamContentType,
  };
  if (init.body) headers["Content-Type"] = "application/json";

  void fetchEventSource(apiUrl(url), {
    method: init.method,
    signal: ctrl.signal,
    openWhenHidden: true,
    headers,
    body: init.body,
    async onopen(res) {
      const ct = res.headers.get("content-type") ?? "";
      if (res.ok && ct.includes(EventStreamContentType)) return;
      if (res.status === 401 || res.status === 429 || res.status >= 500) {
        throw new RetriableError(`stream open failed: ${res.status}`);
      }
      throw new FatalError(
        new ApiError(res.status, await safeText(res)).message,
      );
    },
    onmessage(msg) {
      if (msg.id) lastEventId = msg.id;
      if (!msg.data) return;
      try {
        const parsed = JSON.parse(msg.data) as AgentEvent;
        // `web_*` frames arrive with their own `event:` name; the agent
        // events use `type` inside data which we trust as the union tag.
        if (!parsed.type && msg.event) {
          (parsed as { type: string }).type = msg.event;
        }
        handlers.onEvent(parsed);
      } catch {
        // Ignore unparseable keep-alive comments / partial frames.
      }
    },
    onclose() {
      handlers.onClose?.();
    },
    onerror(err) {
      if (err instanceof FatalError) {
        handlers.onError?.(err);
        throw err; // stop retrying
      }
      // Retriable (network blip / 401 / 5xx): back off and reconnect with
      // a fresh token + Last-Event-ID. Don't surface to the user yet.
      return 1500;
    },
    async fetch(input, init) {
      const token = await getToken();
      const headers = new Headers(init?.headers);
      if (token) headers.set("Authorization", `Bearer ${token}`);
      if (lastEventId) headers.set("Last-Event-ID", lastEventId);
      return fetch(input, { ...init, headers });
    },
  }).catch((err) => {
    if (!(err instanceof FatalError)) handlers.onError?.(err);
  });

  return () => ctrl.abort();
}

async function safeText(res: Response): Promise<string> {
  try {
    return await res.text();
  } catch {
    return `${res.status}`;
  }
}
